all:
	@echo "there is nothing to make with this makefile the makefile is here only to erase the platform dependant data while compiling LaTeX"
	@echo "do <make clean> to do this makefiles intended purpose"

clean:
	rm -rf *.aux
	rm -rf *.fls
	rm -rf *.log
	rm -rf *.out
	rm -rf *.synctex.gz
	rm -rf *.fdb_latexmk
	rm -rf *.bbl
	rm -rf *.bcf
	rm -rf *.blg
	rm -rf *run.xml